version: '3'

services:
  db:
    container_name: app-db_server
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'kGa4rKE5ks'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf/:/etc/mysql/conf.d/my.cnf
      - data_storage:/var/lib/mysql
    ports:
      - "4306:3306"
    networks:
      - common
  app:
    container_name: app-app_server
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - common
    restart: always

volumes:
  data_storage:
    driver: local

networks:
  common:
    driver: bridge